// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file serviceapis/messaging/v1/identity.proto (package serviceapis.messaging.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message serviceapis.messaging.v1.SendVerificationEmailRequest
 */
export class SendVerificationEmailRequest extends Message<SendVerificationEmailRequest> {
  /**
   * @generated from field: string user_id = 1;
   */
  userId = "";

  /**
   * @generated from field: string verification_link = 2;
   */
  verificationLink = "";

  constructor(data?: PartialMessage<SendVerificationEmailRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "serviceapis.messaging.v1.SendVerificationEmailRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "verification_link", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SendVerificationEmailRequest {
    return new SendVerificationEmailRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SendVerificationEmailRequest {
    return new SendVerificationEmailRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SendVerificationEmailRequest {
    return new SendVerificationEmailRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SendVerificationEmailRequest | PlainMessage<SendVerificationEmailRequest> | undefined, b: SendVerificationEmailRequest | PlainMessage<SendVerificationEmailRequest> | undefined): boolean {
    return proto3.util.equals(SendVerificationEmailRequest, a, b);
  }
}

/**
 * @generated from message serviceapis.messaging.v1.SendVerificationEmailResponse
 */
export class SendVerificationEmailResponse extends Message<SendVerificationEmailResponse> {
  /**
   * @generated from field: string message = 1;
   */
  message = "";

  constructor(data?: PartialMessage<SendVerificationEmailResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "serviceapis.messaging.v1.SendVerificationEmailResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SendVerificationEmailResponse {
    return new SendVerificationEmailResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SendVerificationEmailResponse {
    return new SendVerificationEmailResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SendVerificationEmailResponse {
    return new SendVerificationEmailResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SendVerificationEmailResponse | PlainMessage<SendVerificationEmailResponse> | undefined, b: SendVerificationEmailResponse | PlainMessage<SendVerificationEmailResponse> | undefined): boolean {
    return proto3.util.equals(SendVerificationEmailResponse, a, b);
  }
}

/**
 * @generated from message serviceapis.messaging.v1.SendPasswordResetEmailRequest
 */
export class SendPasswordResetEmailRequest extends Message<SendPasswordResetEmailRequest> {
  /**
   * @generated from field: string user_id = 1;
   */
  userId = "";

  /**
   * @generated from field: string password_reset_link = 2;
   */
  passwordResetLink = "";

  constructor(data?: PartialMessage<SendPasswordResetEmailRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "serviceapis.messaging.v1.SendPasswordResetEmailRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "password_reset_link", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SendPasswordResetEmailRequest {
    return new SendPasswordResetEmailRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SendPasswordResetEmailRequest {
    return new SendPasswordResetEmailRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SendPasswordResetEmailRequest {
    return new SendPasswordResetEmailRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SendPasswordResetEmailRequest | PlainMessage<SendPasswordResetEmailRequest> | undefined, b: SendPasswordResetEmailRequest | PlainMessage<SendPasswordResetEmailRequest> | undefined): boolean {
    return proto3.util.equals(SendPasswordResetEmailRequest, a, b);
  }
}

/**
 * @generated from message serviceapis.messaging.v1.SendPasswordResetEmailResponse
 */
export class SendPasswordResetEmailResponse extends Message<SendPasswordResetEmailResponse> {
  /**
   * @generated from field: string message = 1;
   */
  message = "";

  constructor(data?: PartialMessage<SendPasswordResetEmailResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "serviceapis.messaging.v1.SendPasswordResetEmailResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SendPasswordResetEmailResponse {
    return new SendPasswordResetEmailResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SendPasswordResetEmailResponse {
    return new SendPasswordResetEmailResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SendPasswordResetEmailResponse {
    return new SendPasswordResetEmailResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SendPasswordResetEmailResponse | PlainMessage<SendPasswordResetEmailResponse> | undefined, b: SendPasswordResetEmailResponse | PlainMessage<SendPasswordResetEmailResponse> | undefined): boolean {
    return proto3.util.equals(SendPasswordResetEmailResponse, a, b);
  }
}

