// @generated by protoc-gen-connect-es v1.5.0 with parameter "target=ts"
// @generated from file serviceapis/messaging/v1/identity.proto (package serviceapis.messaging.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { SendPasswordResetEmailRequest, SendPasswordResetEmailResponse, SendVerificationEmailRequest, SendVerificationEmailResponse } from "./identity_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service serviceapis.messaging.v1.IdentityMessagingService
 */
export const IdentityMessagingService = {
  typeName: "serviceapis.messaging.v1.IdentityMessagingService",
  methods: {
    /**
     * @generated from rpc serviceapis.messaging.v1.IdentityMessagingService.SendVerificationEmail
     */
    sendVerificationEmail: {
      name: "SendVerificationEmail",
      I: SendVerificationEmailRequest,
      O: SendVerificationEmailResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc serviceapis.messaging.v1.IdentityMessagingService.SendPasswordResetEmail
     */
    sendPasswordResetEmail: {
      name: "SendPasswordResetEmail",
      I: SendPasswordResetEmailRequest,
      O: SendPasswordResetEmailResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

