// @generated by protoc-gen-connect-es v1.5.0 with parameter "target=ts"
// @generated from file serviceapis/identity/v1/identity.proto (package serviceapis.identity.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AuthenticateWithGoogleCodeRequest, AuthenticateWithGoogleCodeResponse, AuthenticateWithPasswordRequest, AuthenticateWithPasswordResponse, CreateUserRequest, CreateUserResponse, GetUserByIdRequest, GetUserByIdResponse, GetUserBySessionTokenRequest, GetUserBySessionTokenResponse } from "./identity_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service serviceapis.identity.v1.IdentityService
 */
export const IdentityService = {
  typeName: "serviceapis.identity.v1.IdentityService",
  methods: {
    /**
     * @generated from rpc serviceapis.identity.v1.IdentityService.GetUserById
     */
    getUserById: {
      name: "GetUserById",
      I: GetUserByIdRequest,
      O: GetUserByIdResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc serviceapis.identity.v1.IdentityService.GetUserBySessionToken
     */
    getUserBySessionToken: {
      name: "GetUserBySessionToken",
      I: GetUserBySessionTokenRequest,
      O: GetUserBySessionTokenResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc serviceapis.identity.v1.IdentityService.CreateUser
     */
    createUser: {
      name: "CreateUser",
      I: CreateUserRequest,
      O: CreateUserResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc serviceapis.identity.v1.IdentityService.AuthenticateWithGoogleCode
     */
    authenticateWithGoogleCode: {
      name: "AuthenticateWithGoogleCode",
      I: AuthenticateWithGoogleCodeRequest,
      O: AuthenticateWithGoogleCodeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc serviceapis.identity.v1.IdentityService.AuthenticateWithPassword
     */
    authenticateWithPassword: {
      name: "AuthenticateWithPassword",
      I: AuthenticateWithPasswordRequest,
      O: AuthenticateWithPasswordResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

